# Form implementation generated from reading ui file 'ui/ui_files/connection_dialog_base.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(491, 160)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 28, 441, 105))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.form_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.form_layout.setContentsMargins(0, 0, 0, 0)
        self.form_layout.setObjectName("form_layout")
        self.connection_button = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.connection_button.setObjectName("connection_button")
        self.form_layout.addWidget(self.connection_button)
        self.message_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.message_label.setStyleSheet("font-size:20px")
        self.message_label.setText("")
        self.message_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.message_label.setObjectName("message_label")
        self.form_layout.addWidget(self.message_label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Connection to JMap Cloud"))
        self.connection_button.setText(_translate("Dialog", "login"))
