# Form implementation generated from reading ui file 'ui/ui_files/export_layer_dialog_base.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(702, 433)
        Dialog.setStyleSheet("background-color:rgb(36, 46, 52)")
        self.jmap_image_label = QtWidgets.QLabel(parent=Dialog)
        self.jmap_image_label.setGeometry(QtCore.QRect(10, 10, 121, 71))
        self.jmap_image_label.setText("")
        self.jmap_image_label.setPixmap(QtGui.QPixmap(":/images/images/Logo_JMap_Cloud.svg"))
        self.jmap_image_label.setObjectName("jmap_image_label")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 100, 681, 321))
        self.widget.setStyleSheet("background-color:rgb(220, 220, 220)\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 661, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        self.title_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.title_label.setStyleSheet("color: black;")
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.project_selection_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_selection_label.sizePolicy().hasHeightForWidth())
        self.project_selection_label.setSizePolicy(sizePolicy)
        self.project_selection_label.setStyleSheet("color: black;")
        self.project_selection_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.project_selection_label.setObjectName("project_selection_label")
        self.verticalLayout.addWidget(self.project_selection_label)
        self.JMap_project_combo_box = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.JMap_project_combo_box.setEnabled(True)
        self.JMap_project_combo_box.setAutoFillBackground(False)
        self.JMap_project_combo_box.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"\n"
"")
        self.JMap_project_combo_box.setObjectName("JMap_project_combo_box")
        self.verticalLayout.addWidget(self.JMap_project_combo_box)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.create_layer_radio_button = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.create_layer_radio_button.setEnabled(False)
        self.create_layer_radio_button.setStyleSheet("QRadioButton { \n"
"    color: black; \n"
"}\n"
"\n"
"QRadioButton:disabled { \n"
"    color: #9e9e9e; \n"
"}")
        self.create_layer_radio_button.setObjectName("create_layer_radio_button")
        self.horizontalLayout.addWidget(self.create_layer_radio_button)
        self.repalce_layer_radio_button = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.repalce_layer_radio_button.setEnabled(False)
        self.repalce_layer_radio_button.setStyleSheet("QRadioButton { \n"
"    color: black; \n"
"}\n"
"\n"
"QRadioButton:disabled { \n"
"    color: #9e9e9e; \n"
"}")
        self.repalce_layer_radio_button.setObjectName("repalce_layer_radio_button")
        self.horizontalLayout.addWidget(self.repalce_layer_radio_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_replace_layer = QtWidgets.QVBoxLayout()
        self.verticalLayout_replace_layer.setObjectName("verticalLayout_replace_layer")
        self.layer_replace_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.layer_replace_label.setEnabled(False)
        self.layer_replace_label.setStyleSheet("QLabel {\n"
"    color: black\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: #9e9e9e;\n"
"}")
        self.layer_replace_label.setObjectName("layer_replace_label")
        self.verticalLayout_replace_layer.addWidget(self.layer_replace_label)
        self.target_layer_replace_combo_box = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.target_layer_replace_combo_box.setEnabled(False)
        self.target_layer_replace_combo_box.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox:disabled {\n"
"    background: #f0f0f0;\n"
"    color: #9e9e9e;\n"
"}\n"
"\n"
"")
        self.target_layer_replace_combo_box.setObjectName("target_layer_replace_combo_box")
        self.verticalLayout_replace_layer.addWidget(self.target_layer_replace_combo_box)
        self.verticalLayout.addLayout(self.verticalLayout_replace_layer)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.error_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.error_label.setStyleSheet("color:rgb(255, 0, 0)")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.export_layer_pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.export_layer_pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_layer_pushButton.sizePolicy().hasHeightForWidth())
        self.export_layer_pushButton.setSizePolicy(sizePolicy)
        self.export_layer_pushButton.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.export_layer_pushButton.setStyleSheet("QPushButton {\n"
"    color: black\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"     color: #9e9e9e; \n"
"}")
        self.export_layer_pushButton.setObjectName("export_layer_pushButton")
        self.verticalLayout.addWidget(self.export_layer_pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Export layer"))
        self.title_label.setText(_translate("Dialog", "Export a layer to JMap Cloud"))
        self.project_selection_label.setText(_translate("Dialog", "Select the Project :"))
        self.create_layer_radio_button.setText(_translate("Dialog", "Create new layer"))
        self.repalce_layer_radio_button.setText(_translate("Dialog", "Replace an existing layer"))
        self.layer_replace_label.setText(_translate("Dialog", "Layer to replace :"))
        self.export_layer_pushButton.setText(_translate("Dialog", "Export"))
