# Form implementation generated from reading ui file 'ui/ui_files/open_project_dialog_base.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets

from ... import resources_rc  # noqa: F401


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(611, 531)
        Dialog.setStyleSheet("background-color:rgb(36, 46, 52)")
        self.jmap_image_label = QtWidgets.QLabel(parent=Dialog)
        self.jmap_image_label.setGeometry(QtCore.QRect(10, 10, 121, 71))
        self.jmap_image_label.setText("")
        self.jmap_image_label.setPixmap(QtGui.QPixmap(":/images/images/Logo_JMap_Cloud.svg"))
        self.jmap_image_label.setObjectName("jmap_image_label")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 100, 591, 421))
        self.widget.setStyleSheet("background-color:rgb(240, 240, 240);\n" "")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.project_List_listWidget = QtWidgets.QListWidget(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.project_List_listWidget.sizePolicy().hasHeightForWidth())
        self.project_List_listWidget.setSizePolicy(sizePolicy)
        self.project_List_listWidget.setStyleSheet(
            "QListWidget {\n"
            " font-size: 17px;\n"
            " background-color: rgb(255, 255, 255);\n"
            " color: rgb(0, 0, 0);\n"
            "}\n"
            "QListWidget::item {\n"
            " color: rgb(0, 0, 0);\n"
            "}\n"
            "QListWidget::item:selected {\n"
            " background-color: rgb(60, 150, 0);\n"
            " color: rgb(255, 255, 255);\n"
            "}"
        )
        self.project_List_listWidget.setIconSize(QtCore.QSize(100, 75))
        self.project_List_listWidget.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.project_List_listWidget.setObjectName("project_List_listWidget")
        self.verticalLayout.addWidget(self.project_List_listWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vector_type_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.vector_type_label.setStyleSheet("border : none;\n" "color:black")
        self.vector_type_label.setObjectName("vector_type_label")
        self.horizontalLayout_2.addWidget(self.vector_type_label)
        self.vector_type_comboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vector_type_comboBox.sizePolicy().hasHeightForWidth())
        self.vector_type_comboBox.setSizePolicy(sizePolicy)
        self.vector_type_comboBox.setAutoFillBackground(False)
        self.vector_type_comboBox.setStyleSheet(
            "QComboBox {\n" "    background-color: white;\n" "    color: black;\n" "}"
        )
        self.vector_type_comboBox.setObjectName("vector_type_comboBox")
        self.vector_type_comboBox.addItem("")
        self.vector_type_comboBox.addItem("")
        self.vector_type_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.vector_type_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.open_project_pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_project_pushButton.sizePolicy().hasHeightForWidth())
        self.open_project_pushButton.setSizePolicy(sizePolicy)
        self.open_project_pushButton.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.open_project_pushButton.setStyleSheet(
            "QPushButton {\n"
            "    color: black\n"
            "}\n"
            "\n"
            "QPushButton:disabled {\n"
            "     color: #9e9e9e; \n"
            "}"
        )
        self.open_project_pushButton.setObjectName("open_project_pushButton")
        self.verticalLayout.addWidget(self.open_project_pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Open Project"))
        self.vector_type_label.setText(_translate("Dialog", " Vector layer type :"))
        self.vector_type_comboBox.setItemText(0, _translate("Dialog", "Default"))
        self.vector_type_comboBox.setItemText(1, _translate("Dialog", "All in GeoJSON"))
        self.vector_type_comboBox.setItemText(2, _translate("Dialog", "All in Vector Tiles"))
        self.open_project_pushButton.setText(_translate("Dialog", "Open project"))
        self.vector_type_comboBox.setItemText(2, _translate("Dialog", "All in Vector Tiles"))
